const APOLLO_SERVER = process.env.APOLLO_SERVER
const APOLLO_SOCKET = process.env.APOLLO_SOCKET
const PAGE_LIMIT = 30
const ZALO_MESSAGE_LIMIT = 15
const NETWORK_STATUS_FETCH_MORE = 3

export {
	APOLLO_SOCKET,
	APOLLO_SERVER,
	NETWORK_STATUS_FETCH_MORE,
	PAGE_LIMIT,
	ZALO_MESSAGE_LIMIT,
}
