const APOLLO_SERVER = process.env.APOLLO_SERVER
const APOLLO_SOCKET = process.env.APOLLO_SOCKET
const PAGE_LIMIT = 30
const NETWORK_STATUS_FETCH_MORE = 3

export { APOLLO_SERVER, PAGE_LIMIT, NETWORK_STATUS_FETCH_MORE, APOLLO_SOCKET }
